CREATE USER -- SENTENCIA PARA CREAR USUARIO

HR -- NOMBRE DEL USUARIO

IDENTIFIED BY Duoc2022_MDY1131 -- CONTRASEÑA

; -- TERMINO DE LA SENTENCIA DE CREACION DEL USUARIO



ALTER USER HR DEFAULT TABLESPACE DATA

QUOTA UNLIMITED ON DATA;



ALTER USER HR TEMPORARY TABLESPACE TEMP;



GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO HR;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO HR;



GRANT EXECUTE ON sys.dbms_stats TO HR;